In [ ]:
#Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/count-card-transactions.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df

       id     transaction_date
0     321  03/03/2025 21:31:00
1     192  29/03/2025 21:35:00
2     251  01/03/2025 21:28:00
3     523  10/03/2025 02:57:00
4     430  11/03/2025 13:21:00
...   ...                  ...
1844  375  03/03/2025 05:12:00
1845  299  26/03/2025 09:03:00
1846  606  06/03/2025 22:54:00
1847  680  26/03/2025 14:35:00
1848  511  03/03/2025 19:00:00

[1849 rows x 2 columns]

In [ ]:
df['transaction_date']  = pd.to_datetime(df['transaction_date'], format='%d/%m/%Y %H:%M:%S')

In [ ]:
df['day'] = df['transaction_date'].dt.day
df['indicator'] = 1

In [ ]:
df.groupby(by=['day'])['indicator'].count()

day
1     73
2     55
3     58
4     54
5     69
6     61
7     62
8     68
9     46
10    53
11    62
12    65
13    55
14    67
15    73
16    54
17    60
18    55
19    66
20    53
21    60
22    51
23    62
24    51
25    57
26    62
27    60
28    58
29    61
30    66
31    52
Name: indicator, dtype: int64

In [ ]:
df.groupby(by=['id'])['indicator'].count()

id
101    2
102    6
103    3
104    3
105    6
      ..
726    2
727    1
728    2
729    5
730    4
Name: indicator, Length: 592, dtype: int64

In [ ]:
# quienes son los que realizan más de 4 transacciones por día
# cuantas transacciones en promeido se realizan por día?s