In [ ]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/stock_price_dataset.csv'

In [ ]:
df = pd.read_csv(url)

In [ ]:
df

  product  price  cost  quantity_available
0       A     10   NaN                 NaN
1       B     30  10.0                 NaN
2       C     40  12.0                10.0
3       D     13   NaN               330.0
4       E      1   0.4                 NaN
5       F     11   8.0               400.0
6       G     33  22.0                33.0
7       H      1   0.1               111.0

In [ ]:
df.isna().sum()

product               0
price                 0
cost                  2
quantity_available    3
dtype: int64

In [ ]:
df.isnull().sum()

product               0
price                 0
cost                  2
quantity_available    3
dtype: int64

In [ ]:
df['product'].isnull().sum()

np.int64(0)

In [ ]:
df['cost'].notna().sum()

np.int64(6)

In [ ]:
df['price'].notna().sum()

np.int64(8)

this information is very imporant.