In [ ]:
# Iván  Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/product_sales_month_U.csv'

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.isnull().sum()

product    0
sales      5
month      0
dtype: int64

In [ ]:
df[df.isnull().sum(axis=1).astype('bool')]

          product  sales  month
41        Almonds    NaN      4
67   Protein bars    NaN      7
90     Mixed nuts    NaN      9
112    Mixed nuts    NaN     11
128  Banana chips    NaN     12

In [ ]:
df['share'] = df['sales']/df.groupby(by=['product'])['sales'].transform('sum')
df['sales_avg'] =  df.groupby(by=['product'])['sales'].transform('mean')
df['rank']= df.groupby(by=['product'])['sales'].rank(method='first')
rank = df[df['rank']<3].sort_values(by='product')
rank

          product  sales  month     share   sales_avg  rank
52        Almonds  682.0      5  0.088698  699.000000   2.0
30        Almonds  678.0      3  0.088178  699.000000   1.0
7    Banana chips  411.0      1  0.089115  419.272727   2.0
29   Banana chips  400.0      3  0.086730  419.272727   1.0
108       Cashews  397.0     10  0.081169  407.583333   2.0
119       Cashews  384.0     11  0.078512  407.583333   1.0
81    Dried fruit  522.0      8  0.082088  529.916667   2.0
70    Dried fruit  517.0      7  0.081302  529.916667   1.0
55   Granola bars  376.0      6  0.078925  397.000000   1.0
77   Granola bars  388.0      8  0.081444  397.000000   2.0
35     Mixed nuts  758.0      4  0.097404  778.200000   1.0
57     Mixed nuts  768.0      6  0.098689  778.200000   2.0
17     Pistachios  786.0      2  0.081841  800.333333   2.0
83     Pistachios  785.0      8  0.081737  800.333333   1.0
12   Protein bars  678.0      2  0.089352  689.818182   1.0
23   Protein bars  678.0      3  0.089352  689.818182   2.0
5      Rice cakes  434.0      1  0.081304  444.833333   2.0
126    Rice cakes  432.0     12  0.080929  444.833333   1.0
36      Trail mix  647.0      4  0.082232  655.666667   2.0
80      Trail mix  628.0      8  0.079817  655.666667   1.0
65        Walnuts  275.0      6  0.080716  283.916667   2.0
10        Walnuts  275.0      1  0.080716  283.916667   1.0

In [ ]:
df[df['product']=='Granola bars']['sales'].mean()

np.float64(397.0)

In [ ]:
df.drop_duplicates(subset=['product'], keep='first')[['product','sales_avg']]

         product   sales_avg
0   Granola bars  397.000000
1   Protein bars  689.818182
2     Mixed nuts  778.200000
3      Trail mix  655.666667
4    Dried fruit  529.916667
5     Rice cakes  444.833333
6     Pistachios  800.333333
7   Banana chips  419.272727
8        Almonds  699.000000
9        Cashews  407.583333
10       Walnuts  283.916667