In [ ]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/price-quantities-U.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.columns

Index(['Date', 'price_registred_', 'promotion_day',
       'month_extracted_from_Date', 'quantity_sold', 'unitary_cost',
       'ref_transaction', 'stock'],
      dtype='object')

In [ ]:
df.drop(columns = ['ref_transaction', 'stock'], inplace=True)

In [ ]:
df.rename(columns={
    'price_registred_':'price',
    'month_extracted_from_Date':'month',
    'quantity_sold':'quantity'
}, inplace=True)

In [ ]:
df.sort_values(by=['quantity'], ascending=False)[0:5]

           Date  price promotion_day     month  quantity  unitary_cost
351  2025-12-18   32.0            No  December       746          7.61
356  2025-12-23   31.0            No  December       710          7.45
350  2025-12-17   32.0            No  December       698          7.49
360  2025-12-27   32.0            No  December       691          8.42
347  2025-12-14   32.0            No  December       691          8.03

In [ ]:
df['promotion_day'].value_counts(normalize=True)

promotion_day
No     0.868493
Yes    0.131507
Name: proportion, dtype: float64

In [ ]:
df[df['month'] == 'December']['quantity'].mean()

np.float64(651.0645161290323)

In [ ]:
df['profit'] = df['quantity'] *  (df['price'] - df['unitary_cost'])

In [ ]:
df[df['month']=='January']['profit'].mean()  - df[df['month']=='December']['profit'].mean()

np.float64(-8817.319677419353)