In [ ]:
# Iván Andrés Trujillo Abella
#ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/Spent_ref_customer-U.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df

    customer ref_product  total_spent
0          1         F17        54.87
1          2         I10        81.45
2          3          C6       215.01
3          4          B6       114.80
4          5         J16       143.90
..       ...         ...          ...
94        95         A10        96.51
95        96         J13       143.90
96        97          K6       250.77
97        98          D6        98.75
98        99         F19        54.87

[99 rows x 3 columns]

In [ ]:
df['ref'] = df['ref_product'].apply(lambda x: x[0])

In [ ]:
df.groupby(by=['ref'])['total_spent'].sum().sort_values(ascending=False)[0:3]

ref
E    2416.11
K    2256.93
H    1791.44
Name: total_spent, dtype: float64