In [14]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [15]:
import pandas as pd

In [16]:
url1="https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/sem1.csv"
url2="https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/sem2.csv"

In [17]:
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)

In [18]:
full = pd.concat([df1,df2])

In [27]:
full

     month id-product id
0        1        A23  A
1        1        C34  C
2        1        B35  B
3        1        D52  D
4        1        D21  D
..     ...        ... ..
597     12        D43  D
598     12        B33  B
599     12        C43  C
600     12        D50  D
601     12        B33  B

[1200 rows x 3 columns]

In [24]:
full['id'] = full['id-product'].apply(lambda x: x[0])

In [31]:
full.groupby(by=['month','id']).count()

          id-product
month id
1     A            4
      B            3
      C           14
      D           22
      E            1
2     A            7
      B           10
      C           22
      D           39
      E            7
3     A            8
      B           16
      C           26
      D           41
      E            2
4     A           15
      B           18
      C           24
      D           53
      E            8
5     A           12
      B           24
      C           39
      D           80
      E            9
6     A           12
      B            7
      C           21
      D           48
      E            6
7     A           10
      B           14
      C           37
      D           66
      E           12
8     A           13
      B           13
      C           26
      D           38
      E            3
9     A            4
      B            6
      C           14
      D           18
      E            2
10    A            7
      B            8
      C           14
      D           34
      E            5
11    A            8
      B           11
      C           30
      D           56
      E            2
12    A           14
      B           26
      C           34
      D           73
      E            4

In [34]:
full[full['id'] == 'A']['month'].value_counts()

month
4     15
12    14
8     13
6     12
5     12
7     10
3      8
11     8
10     7
2      7
1      4
9      4
Name: count, dtype: int64