In [10]:
# ivan andrés trujillo abella
# ivantrujillo1229@gmail.com

por lo general lo importado es mas bárato pero eso puede gnerera costos de pérdida volatilidad, etc, nuestro objetivo es saber si es mejor o no en términos de costo.

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy

In [12]:
url = 'https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/supplier_cost_mba.csv'

In [13]:
df = pd.read_csv(url)

In [14]:
df

     supplier   total_cost
0    domestic  1199.980164
1    domestic  1202.463645
2    domestic  1200.995986
3    domestic  1200.286285
4    domestic  1199.642903
..        ...          ...
175  imported  1301.012874
176  imported  1300.647523
177  imported  1297.787068
178  imported  1300.991879
179  imported  1298.383776

[180 rows x 2 columns]

In [15]:
df.groupby(by=['supplier'])['total_cost'].mean()

supplier
domestic    1199.973469
imported    1299.889205
Name: total_cost, dtype: float64

In [16]:
scipy.stats.ttest_ind(df[df['supplier']=='domestic']['total_cost'],
                      df[df['supplier']=='imported']['total_cost'], equal_var=True ).pvalue

np.float64(7.091713755895311e-257)